services:
  mongodb:
    image: mongo:latest
    container_name: the-daily-web-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: the-daily-web
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
